# Autogenerated by tools/build/setup_cmake.py
# from tools/build/cmake_templates/Dependency.cmake
# Do not edit - any changes will be lost!

if(DEFINED IMP_NO_TTTRLIB)
 message("tttrlib not found")
file(WRITE "${CMAKE_BINARY_DIR}/build_info/tttrlib" "ok=False")
else(DEFINED IMP_NO_TTTRLIB)
set(CHECK_COMPILES_BODY "tttrlib::data::ExpressionEngine e; e.compile(\"1+1\");")

include(LibFindMacros)

# Use pkg-config to get hints about paths
# If there are multiple .pc files to try, try each one in turn until
# we get a result
foreach (pkg tttrlib)
  libfind_pkg_check_modules("TTTRLIB_PKGCONF" ${pkg})
  if (NOT "${TTTRLIB_PKGCONF_INCLUDE_DIRS}" STREQUAL "")
    break()
  endif()
endforeach(pkg)

# Include dir
find_path("TTTRLIB_INCLUDE_DIR"
  NAMES tttrlib/ExpressionEngine.h
  PATHS ${TTTRLIB_PKGCONF_INCLUDE_DIRS}
)

# Finally the library itself
# On Windows CMake does not search the 'lib' prefix, so manually add that;
# otherwise it will fail to find, e.g. libprotobuf.lib
foreach(lib )
  if(WIN32)
    find_library("${lib}_LIBRARY"
      NAMES ${lib} lib${lib}
      PATHS ${TTTRLIB_PKGCONF_LIBRARY_DIRS}
    )
  else()
    find_library("${lib}_LIBRARY"
      NAMES ${lib}
      PATHS ${TTTRLIB_PKGCONF_LIBRARY_DIRS}
    )
  endif()
  list(APPEND TTTRLIB_LIBRARY "${${lib}_LIBRARY}")
endforeach(lib)


# Set the include dir variables and the libraries and let libfind_process do the rest.
# NOTE: Singular variables for this library, plural for libraries that this lib depends on.
set(TTTRLIB_PROCESS_INCLUDES TTTRLIB_INCLUDE_DIR)
set(TTTRLIB_PROCESS_LIBS TTTRLIB_LIBRARY)

# clear target variable
set(TTTRLIB_LIBRARIES "" CACHE INTERNAL "")
libfind_process(TTTRLIB)

if ("${TTTRLIB_LIBRARY}" MATCHES ".*NOTFOUND.*"
    OR "${TTTRLIB_INCLUDE_DIR}" MATCHES ".*NOTFOUND.*")
  message("tttrlib not found")
file(WRITE "${CMAKE_BINARY_DIR}/build_info/tttrlib" "ok=False")
else()
  check_compiles("_found" "tttrlib" "TTTRLIB" "#include <tttrlib/ExpressionEngine.h>" "${TTTRLIB_INCLUDE_DIR}" "${TTTRLIB_LIBRARIES}" TTTRLIB_ok_ok)
  if(${TTTRLIB_ok_ok} MATCHES "1")
    message(STATUS "Found tttrlib")
    set(IMP_ALL_DEPENDS_VARS ${IMP_ALL_DEPENDS_VARS} "TTTRLIB_INCLUDE_PATH" "TTTRLIB_LIBRARIES" CACHE INTERNAL "" FORCE)
  else()
    message("tttrlib not found")
file(WRITE "${CMAKE_BINARY_DIR}/build_info/tttrlib" "ok=False")
  endif()
endif()


endif(DEFINED IMP_NO_TTTRLIB)
