stages:
  - build
  - test
  - deploy

.build_psx: &build_psx
  stage: build
  script:
    - git submodule update --init --recursive --remote
    - ./tools/build.sh
  artifacts:
    paths:
      - bld-dir/
build:lnx_x86_64:
  <<: *build_psx
  image:
    name: condaforge/linux-anvil-comp7
    entrypoint: [ "/bin/bash", "-i", "-c" ]
  tags:
    - x86_64
  before_script:
    - conda init bash
    - conda activate /opt/conda/
    - git submodule update --init --recursive --remote
#build:lnx_ppc64le:
#  <<: *build_psx
#  image:
#    name: condaforge/linux-anvil-ppc64le
#    entrypoint: [ "/bin/bash", "-i", "-c" ]
#  before_script:
#    - /opt/conda/bin/tini -- /opt/docker/bin/entrypoint
#    - git submodule update --init --recursive --remote
#  tags:
#    - ppc64le
#build:lnx_aarch64:
#  <<: *build_psx
#  image:
#    name: condaforge/linux-anvil-aarch64
#    entrypoint: [ "/bin/bash", "-i", "-c" ]
#  before_script:
#    - /opt/conda/bin/tini -- /opt/docker/bin/entrypoint
#    - git submodule update --init --recursive --remote
#  tags:
#    - aarch64
build:osx:
  <<: *build_psx
  tags:
    - osx

build:windows:
  stage: build
  tags:
    - win
  before_script:
    - git submodule update --init --recursive --remote
  script:
    - ./tools/build.bat
  artifacts:
    paths:
      - bld-dir/


test:linux:
  stage: test
  tags:
    - linux
  image: condaforge/mambaforge
  needs: ["build:lnx_x86_64"]
  script:
    - source activate base
    - conda config --add channels "file://`pwd`/bld-dir"
    - mamba install python imp.bff nose numba numpy
    - nosetests test

deploy:conda:
  stage: deploy
  image: condaforge/mambaforge
  tags:
    - linux
  before_script:
    - git submodule update --init --recursive --remote
  script:
    - source activate
    - mamba install anaconda-client
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then DEPLOY_LABEL=main; else DEPLOY_LABEL=nightly; fi
    - anaconda -t ${ANACONDA_API_TOKEN} upload -l ${DEPLOY_LABEL} -u ${CONDA_USER} --force bld-dir/**/*.tar.bz2
