variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4

stages:
  - build
  - test
  - deploy

.build: &build
  stage: build
  artifacts:
    paths:
      - bld-dir/
.build_posix: &build_posix
  <<: *build
  script:
    - git submodule update --init --recursive --remote
    - ./tools/build.sh
.build:lnx: &build_lnx
  <<: *build_posix
  before_script:
    - source "/opt/conda/etc/profile.d/conda.sh"
    - conda activate /opt/conda/
    - git submodule update --init --recursive --remote
build:lnx_x86:
  <<: *build_lnx
  image:
    name: condaforge/linux-anvil-cos7-x86_64
    entrypoint: [ "/bin/bash", "-i", "-c" ]
  tags:
    - x86_64
# No PPC or ARM64 IMP builds
#build:lnx_ppc64le:
#  <<: *build_lnx
#  image:
#    name: condaforge/linux-anvil-ppc64le
#    entrypoint: [ "/bin/bash", "-i", "-c" ]
#  tags:
#    - ppc64le
#build:lnx_aarch64:
#  <<: *build_lnx
#  image:
#    name: condaforge/linux-anvil-aarch64
#    entrypoint: [ "/bin/bash", "-i", "-c" ]
#  tags:
#    - aarch64

build:osx:
  <<: *build_posix
  before_script:
    - git submodule update --init --recursive --remote
  tags:
    - osx

build:windows:
  <<: *build
  image: mambaforge:vs16
  tags:
    - win
  before_script:
    - echo "Before SSSSSS"
    - git config --global --add safe.directory *
    - git submodule update --init --recursive --remote
  script:
    - Init64.ps1
    - ./tools/build.bat

test:linux:
  stage: test
  tags:
    - linux
  image: condaforge/mambaforge
  needs: ["build:lnx_x86"]
  script:
    - source activate base
    - conda config --add channels "file://`pwd`/bld-dir"
    - mamba install python imp.bff nose numba numpy mongodb pandas
    - mkdir db & nohup mongod --dbpath db &
    - cd test
    - nosetests

deploy:conda:
  stage: deploy
  image: condaforge/mambaforge
  tags:
    - linux
  before_script:
    - git submodule update --init --recursive --remote
  script:
    - source activate
    - mamba install anaconda-client
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then DEPLOY_LABEL=main; else DEPLOY_LABEL=nightly; fi
    - anaconda -t ${ANACONDA_API_TOKEN} upload -l ${DEPLOY_LABEL} -u ${CONDA_USER} --force bld-dir/**/*.tar.bz2
