stages:
- build
- test
- deploy
- trigger-cross-projects

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DEPLOY_VARIABLE: "nightly"
  MINICONDA_VERSION: "latest"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /master/
      variables:
        DEPLOY_VARIABLE: "main"  # Override globally-defined DEPLOY_VARIABLE
    - when: always               # Run the pipeline in other cases


build:linux:
  image: continuumio/miniconda3:latest
  stage: build
  tags:
    - linux
  before_script:
    - apt update -yq && apt -yq install build-essential cmake
  script:
    - echo "I am the build stage."
    - source activate base
    - conda install imp -c salilab
    - mkdir build
    - cd build 
    - cmake ..
  # artifacts:
  #   expire_in: 7 days
  #   paths:
  #     - bld-dir/

# test:linux:
#   image: ubuntu:18.04
#   before_script:
#     - export DEBIAN_FRONTEND=noninteractive
#     - apt update -yq
#     - apt install -yq procps wget git git-lfs
#     # Download and install miniconda
#     - wget https://repo.continuum.io/miniconda/Miniconda3-$MINICONDA_VERSION-$MINICONDA_OS-x86_64.sh -O miniconda.sh
#     - bash miniconda.sh -b -p $HOME/miniconda
#     - export PATH="$HOME/miniconda/bin:$PATH"
#     # setup conda to always accept commands
#     - conda config --set always_yes yes --set changeps1 no
#   script:
#     - echo "I am a test stage."
#     - source activate base
#     - conda install mamba conda-verify -c conda-forge
#     - |
#       conda config --add channels salilab
#       conda config --add channels "file://`pwd`/bld-dir"
#     - mamba create -n test python=3.8
#     - conda activate test
#     - mamba install tttrlib nose scipy
#     - git clone https://gitlab.peulen.xyz/tpeulen/tttr-data --depth 1
#     - |
#       cd test
#       nosetests

# deploy:
#   image: continuumio/miniconda3:latest
#   stage: deploy
#   tags:
#     - linux
#   dependencies:
#     - build:linux
#   script:
#     - echo "I am a depolyment stage job."
#     - source activate base
#     - conda install anaconda-client
#     - anaconda -t ${ANACONDA_API_TOKEN} upload -l ${DEPLOY_VARIABLE} -u ${CONDA_USER} --force bld-dir/linux-64/*.tar.bz2


# # Downstream projects
# imp:
#   stage: trigger-cross-projects
#   trigger: tpeulen/imp

