# Autogenerated by tools/build/setup_cmake.py
# from tools/build/cmake_templates/Module.cmake
# Do not edit - any changes will be lost!

project(IMP.fluorescence)

include(${CMAKE_SOURCE_DIR}/Setup.cmake)

imp_get_process_exit_code("Setting up module fluorescence" status ${CMAKE_BINARY_DIR}
                          COMMAND ${PYTHON_EXECUTABLE}
                          /home/tpeulen/miniconda3/share/IMP/tools/build/setup_module.py
                          --build_dir=/home/tpeulen/miniconda3/share/IMP/build_info  --name=fluorescence
                          --datapath=${IMP_DATAPATH}
                          --defines=${IMP_fluorescence_CONFIG}:
                          --source=${CMAKE_SOURCE_DIR}
                          )

if(${status} EQUAL 0)
  imp_execute_process("setup_swig_wrappers fluorescence" ${CMAKE_BINARY_DIR}
    COMMAND ${PYTHON_EXECUTABLE} /home/tpeulen/miniconda3/share/IMP/tools/build/setup_swig_wrappers.py
    --build_dir=/home/tpeulen/miniconda3/share/IMP/build_info  --module=fluorescence
    --datapath=${IMP_DATAPATH}
    --source=${CMAKE_SOURCE_DIR})

  # for warning control
  add_definitions(-DIMPFLUORESCENCE_COMPILATION)

  if(0 EQUAL 0)
    set(allh_command  "${PYTHON_EXECUTABLE}" "/home/tpeulen/miniconda3/share/IMP/tools/dev_tools/make_all_header.py" "${CMAKE_BINARY_DIR}/include/IMP/fluorescence.h" "IMP/fluorescence" "${PROJECT_SOURCE_DIR}/include/" ${IMP_fluorescence_EXTRA_HEADERS})
    # for swig
    imp_execute_process("IMP.fluorescence making all header" ${PROJECT_BINARY_DIR}
                        COMMAND ${allh_command})

    add_custom_target(IMP.fluorescence-all-header
      COMMAND ${allh_command}
      DEPENDS "/home/tpeulen/miniconda3/share/IMP/tools/dev_tools/make_all_header.py")
    set_property(TARGET "IMP.fluorescence-all-header" PROPERTY FOLDER "IMP.fluorescence")
    list(APPEND IMP_fluorescence_LIBRARY_EXTRA_DEPENDENCIES IMP.fluorescence-all-header)
  endif()

  
  if(IMP_DOXYGEN_FOUND)
    # documentation
    file(GLOB headers ${CMAKE_BINARY_DIR}/include/IMP/fluorescence/*.h)
    file(GLOB docs ${CMAKE_SOURCE_DIR}/doc/*.dox
      ${CMAKE_SOURCE_DIR}/doc/*.md)
    file(GLOB examples ${CMAKE_BINARY_DIR}/doc/examples/fluorescence/*.py
      ${CMAKE_BINARY_DIR}/doc/examples/fluorescence/*.cpp)

    if(NOT IMP_STATIC)
      set(IMP_fluorescence_TAG_DEPENDS "${IMP.fluorescence-python}")
    endif()

    add_custom_command(OUTPUT ${CMAKE_BINARY_DIR}/doxygen/fluorescence/tags ${CMAKE_BINARY_DIR}/doxygen/fluorescence/xml/index.xml
      COMMAND mkdir -p ${CMAKE_BINARY_DIR}/doc/html
      COMMAND ln -s -f ../../include
      COMMAND ln -s -f ../../doc/examples
      COMMAND ln -s -f ../../lib
      COMMAND ${IMP_DOXYGEN_EXECUTABLE} ../../doxygen/fluorescence/Doxyfile 2>&1 /dev/null
      COMMAND ${PYTHON_EXECUTABLE} /home/tpeulen/miniconda3/share/IMP/tools/build/doxygen_patch_tags.py --module=fluorescence --file=../../doxygen/fluorescence/tags
      COMMAND ${PYTHON_EXECUTABLE} /home/tpeulen/miniconda3/share/IMP/tools/build/doxygen_show_warnings.py --warn=../../doxygen/fluorescence/warnings.txt
      COMMAND ${PYTHON_EXECUTABLE} /home/tpeulen/miniconda3/share/IMP/tools/build/doxygen_spell_check.py xml ${CMAKE_SOURCE_DIR}/test/standards_exceptions
      DEPENDS  ${headers} ${docs} ${examples} ${CMAKE_SOURCE_DIR}/README.md ${IMP_fluorescence_TAG_DEPENDS}
      WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/doxygen/fluorescence/
      COMMENT "Running doxygen on fluorescence")

    add_custom_target("IMP.fluorescence-doc" ALL DEPENDS ${CMAKE_BINARY_DIR}/doxygen/fluorescence/tags)
    set_property(TARGET "IMP.fluorescence-doc" PROPERTY FOLDER "IMP.fluorescence")
    set(IMP_fluorescence_DOC "IMP.fluorescence-doc" CACHE INTERNAL "" FORCE)

    if(NOT IMP_STATIC)
      list(APPEND IMP_DOC_DEPENDS "${IMP.fluorescence-python}")
    endif()
    list(REMOVE_DUPLICATES IMP_DOC_DEPENDS)
    set(IMP_DOC_DEPENDS ${IMP_DOC_DEPENDS} CACHE INTERNAL "" FORCE)
  else()
    set(IMP_fluorescence_DOC "" CACHE INTERNAL "" FORCE)
  endif(IMP_DOXYGEN_FOUND)

  if(0 EQUAL 0)
    list(APPEND imp_fluorescence_libs )
    list(APPEND imp_fluorescence_libs )
    list(REMOVE_DUPLICATES imp_fluorescence_libs)

    add_custom_command(
	OUTPUT ${CMAKE_BINARY_DIR}/lib/IMP/fluorescence/_version_check.py
               ${CMAKE_BINARY_DIR}/src/fluorescence_config.cpp
        COMMAND ${PYTHON_EXECUTABLE} /home/tpeulen/miniconda3/share/IMP/tools/build/make_module_version.py
	        --name=fluorescence --datapath=${IMP_DATAPATH}
		--source=${CMAKE_SOURCE_DIR}
        DEPENDS IMP-version
        WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/
        COMMENT "Building module version info")

    add_custom_target("IMP.fluorescence-version" ALL DEPENDS
                      ${CMAKE_BINARY_DIR}/lib/IMP/fluorescence/_version_check.py
                      ${CMAKE_BINARY_DIR}/src/fluorescence_config.cpp)
    set_property(TARGET "IMP.fluorescence-version" PROPERTY FOLDER "IMP.fluorescence")
    install(FILES "${CMAKE_BINARY_DIR}/lib/IMP/fluorescence/_version_check.py"
	    DESTINATION "${CMAKE_INSTALL_PYTHONDIR}/IMP/fluorescence/")
   endif()

  add_subdirectory(${CMAKE_SOURCE_DIR}/src)
add_subdirectory(${CMAKE_SOURCE_DIR}/test)
add_subdirectory(${CMAKE_SOURCE_DIR}/examples)
add_subdirectory(${CMAKE_SOURCE_DIR}/benchmark)
add_subdirectory(${CMAKE_SOURCE_DIR}/bin)
add_subdirectory(${CMAKE_SOURCE_DIR}/utility)
  set(IMP_fluorescence "IMP.fluorescence" CACHE INTERNAL "" FORCE)
else()

  # make sure it is empty
  set(IMP_fluorescence_DOC "" CACHE INTERNAL "" FORCE)
  set(IMP_fluorescence_PYTHON "" CACHE INTERNAL "" FORCE)
  set(IMP_fluorescence "" CACHE INTERNAL "" FORCE)

  if(${status} EQUAL 1)
    message(FATAL_ERROR "Module IMP.fluorescence disabled")
  else()
    message(FATAL_ERROR "setup_module returned ${status}")
  endif()
  set(IMP_fluorescence_LIBRARY CACHE INTERNAL "" FORCE)
endif()
