"""The fps.json schema — the single authored definition (PRD-97 stage 0).

fps.json describes labelling positions and distance measurements on a
structure. Historically it had three readers (the C++
``IMP::bff::AVNetworkRestraint``/``FPSReaderWriter``, a small Python reader,
and ChiSurf's elaborate one) and **no definition**: two dialects existed whose
field sets differed, and a file written by one was not fully readable by the
other. This module is the definition. It follows mmfdb's discipline — the
schema is *one authored artifact* and everything else derives from it:

* :data:`POSITION_FIELDS` / :data:`DISTANCE_FIELDS` name every field either
  dialect uses, with type, default, and — where the flrCIF dictionary defines
  the concept — the canonical flrCIF item name. Where flrCIF has no item, the
  entry is an authored local definition, visible here rather than implied by a
  parser.
* :func:`to_json_schema` derives a JSON-Schema document from the field tables;
  the shipped ``data/fps_json_schema.json`` is generated by it and a test
  holds the two in agreement (drift guardrail, like mmfdb's).
* :func:`validate` checks a parsed fps.json payload against the definition —
  readers and writers are checked against the schema, not against each other.

Top-level layout of an fps.json (the "network" dialect)::

    {
      "Positions":  {"<name>": {<position fields>}, ...},
      "Distances":  {"<name>": {<distance fields>}, ...},
      "χ²":         {"<set name>": {"distances": ["<name>", ...]}, ...},
      "Evaluators": [ {...}, ... ],          # optional, application-defined
      ...                                     # extra keys are preserved
    }

The second dialect ("flat", the template files in ``data/``) is a single
position object with no wrapper — the same position fields, validated by
:func:`validate_position`.

References: the flrCIF extension dictionary (mmCIF ``ihm_flr`` extension),
categories ``_flr_FPS_AV_parameter``, ``_flr_FPS_global_parameter``,
``_flr_FPS_mean_probe_position`` and ``_flr_fret_distance_restraint``.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Tuple

__all__ = [
    "SCHEMA_VERSION",
    "POSITION_FIELDS",
    "DISTANCE_FIELDS",
    "SCORE_SET_FIELDS",
    "SIMULATION_TYPES",
    "DISTANCE_TYPES",
    "to_json_schema",
    "validate",
    "validate_position",
    "validate_distance",
]

SCHEMA_VERSION = "1.0"

#: ``simulation_type`` values. AV1: one dye radius; AV3: three; XYZ: a fixed
#: mean position (no volume simulation), carried by legacy C# FPS conversions.
SIMULATION_TYPES = ("AV1", "AV3", "XYZ")

#: ``distance_type`` values and their flrCIF ``distance_type`` spellings.
#: RDAMean = mean inter-dye distance <R_DA>; RDAMeanE = FRET-averaged distance
#: <R_DA>_E; Rmp = distance between mean dye positions R_mp.
DISTANCE_TYPES = {
    "RDAMean": "<R_DA>",
    "RDAMeanE": "<R_DA>_E",
    "Rmp": "R_mp",
}

# ---------------------------------------------------------------------------
# Field tables
#
# Each entry: name -> {
#   "type":     python type or tuple of accepted types,
#   "default":  value a reader may assume when the key is absent
#               (None = no default; the key is then required for the dialects
#                listed in "required_for"),
#   "flrcif":   canonical flrCIF item name, or None when flrCIF does not
#               define the concept (then "authored" documents the local
#               definition),
#   "dialects": which historical dialect(s) carried the key
#               ("network" = ChiSurf Positions/Distances files,
#                "flat" = imp.bff template files, "csfps" = values produced by
#                converting legacy C# FPS .txt input),
# }
# ---------------------------------------------------------------------------

_S, _F, _I, _B = str, float, int, bool

POSITION_FIELDS: Dict[str, Dict[str, Any]] = {
    # --- labelling site --------------------------------------------------
    "chain_identifier": dict(
        type=_S, default="", flrcif=None,
        authored="Chain (asym) id of the attachment atom; empty matches any.",
        dialects=("network", "flat")),
    "residue_seq_number": dict(
        type=_I, default=0, flrcif=None,
        authored="Author residue sequence number of the attachment atom.",
        dialects=("network", "flat")),
    "residue_name": dict(
        type=_S, default="", flrcif=None,
        authored="Residue name of the attachment atom (informational).",
        dialects=("flat",)),
    "atom_name": dict(
        type=_S, default="CA", flrcif=None,
        authored="Atom name the dye linker attaches to (e.g. CA, CB).",
        dialects=("network", "flat")),
    # --- AV geometry (flrCIF FPS AV parameters) --------------------------
    "linker_length": dict(
        type=_F, default=20.0, flrcif="_flr_FPS_AV_parameter.linker_length",
        dialects=("network", "flat")),
    "linker_width": dict(
        type=_F, default=0.5, flrcif="_flr_FPS_AV_parameter.linker_width",
        dialects=("network", "flat")),
    "radius1": dict(
        type=_F, default=3.5, flrcif="_flr_FPS_AV_parameter.probe_radius_1",
        dialects=("network", "flat")),
    "radius2": dict(
        type=_F, default=0.0, flrcif="_flr_FPS_AV_parameter.probe_radius_2",
        dialects=("network", "flat")),
    "radius3": dict(
        type=_F, default=0.0, flrcif="_flr_FPS_AV_parameter.probe_radius_3",
        dialects=("network", "flat")),
    "simulation_type": dict(
        type=_S, default="AV1", flrcif=None, enum=SIMULATION_TYPES,
        authored="AV model: AV1 (one radius), AV3 (three radii), or XYZ "
                 "(fixed mean position, no simulation).",
        dialects=("network", "flat", "csfps")),
    "simulation_grid_resolution": dict(
        type=_F, default=1.5, flrcif=None,
        authored="AV grid spacing in Angstrom. Related to (but not the same "
                 "item as) _flr_FPS_global_parameter.AV_min_grid_A, which is "
                 "the *minimum* grid constant of FPS's relative-grid scheme.",
        dialects=("network", "flat")),
    # --- accessible-contact-volume extensions (imp.bff dialect) ----------
    "allowed_sphere_radius": dict(
        type=_F, default=1.5,
        flrcif="_flr_FPS_global_parameter.AV_allowed_sphere",
        dialects=("flat",)),
    "contact_volume_thickness": dict(
        type=_F, default=0.0, flrcif=None,
        authored="Thickness of the contact layer above the molecular surface "
                 "for accessible-contact-volume (ACV) weighting; 0 disables.",
        dialects=("flat",)),
    "contact_volume_trapped_fraction": dict(
        type=_F, default=-1.0, flrcif=None,
        authored="Fraction of dye density trapped in the contact volume; "
                 "negative disables ACV re-weighting.",
        dialects=("flat",)),
    "min_sphere_volume_fraction": dict(
        type=_F, default=0.0, flrcif=None,
        authored="Minimum accessible fraction of the free-dye sphere volume "
                 "below which a position is flagged as buried.",
        dialects=("flat",)),
    "anchor_atoms": dict(
        type=_S, default="", flrcif=None,
        authored="Explicit anchor atom names overriding the default linker "
                 "anchor search (comma separated).",
        dialects=("flat",)),
    "strip_mask": dict(
        type=_S, default="", flrcif=None,
        authored="Selection mask of atoms removed as obstacles before the AV "
                 "simulation (e.g. flexible tags).",
        dialects=("flat",)),
    "chain_weighting": dict(
        type=_B, default=False, flrcif=None,
        authored="Weight AV grid points by linker-chain statistics instead "
                 "of uniformly.",
        dialects=("flat",)),
    # --- rigid-body / multi-body assignment (ChiSurf dialect) ------------
    "body_id": dict(
        type=_I, default=0, flrcif=None,
        authored="Index of the rigid body (input PDB) this position labels; "
                 "docking moves bodies relative to each other.",
        dialects=("network", "csfps")),
    # --- fixed positions (XYZ simulation_type, legacy C# conversions) ----
    "x": dict(
        type=_F, default=None, flrcif="_flr_FPS_mean_probe_position.mpp_xcoord",
        dialects=("csfps",)),
    "y": dict(
        type=_F, default=None, flrcif="_flr_FPS_mean_probe_position.mpp_ycoord",
        dialects=("csfps",)),
    "z": dict(
        type=_F, default=None, flrcif="_flr_FPS_mean_probe_position.mpp_zcoord",
        dialects=("csfps",)),
}

DISTANCE_FIELDS: Dict[str, Dict[str, Any]] = {
    "position1_name": dict(
        type=_S, default=None,
        flrcif="_flr_fret_distance_restraint.sample_probe_id_1",
        required=True, dialects=("network", "flat")),
    "position2_name": dict(
        type=_S, default=None,
        flrcif="_flr_fret_distance_restraint.sample_probe_id_2",
        required=True, dialects=("network", "flat")),
    "distance": dict(
        type=_F, default=None,
        flrcif="_flr_fret_distance_restraint.distance",
        required=True, dialects=("network", "flat")),
    "error_neg": dict(
        type=_F, default=None,
        flrcif="_flr_fret_distance_restraint.distance_error_minus",
        required=True, dialects=("network", "flat")),
    "error_pos": dict(
        type=_F, default=None,
        flrcif="_flr_fret_distance_restraint.distance_error_plus",
        required=True, dialects=("network", "flat")),
    "distance_type": dict(
        type=_S, default="RDAMean",
        flrcif="_flr_fret_distance_restraint.distance_type",
        enum=tuple(DISTANCE_TYPES), dialects=("network", "flat")),
    "Forster_radius": dict(
        type=_F, default=52.0,
        flrcif="_flr_fret_forster_radius.forster_radius",
        dialects=("network", "flat")),
}

#: A score set (the "χ²" top-level section) selects a named subset of the
#: distances to score together. flrCIF groups restraints via
#: ``_flr_fret_distance_restraint.group_id``; the named-set spelling here is
#: the authored fps.json form of the same concept.
SCORE_SET_FIELDS: Dict[str, Dict[str, Any]] = {
    "distances": dict(
        type=list, default=None,
        flrcif="_flr_fret_distance_restraint.group_id",
        required=True,
        authored="Names of the Distances entries belonging to this set."),
    "maximum_NaNs_allowed": dict(
        type=_I, default=None, flrcif=None,
        authored="Olga screening: maximum number of NaN model distances "
                 "tolerated before a structure's score set is rejected.",
        dialects=("network",)),
    "penalty_NaN": dict(
        type=_F, default=None, flrcif=None,
        authored="Olga screening: chi-square penalty added per NaN model "
                 "distance.",
        dialects=("network",)),
}


# ---------------------------------------------------------------------------
# Derivation: JSON Schema
# ---------------------------------------------------------------------------

_JSON_TYPES = {_S: "string", _F: "number", _I: "integer", _B: "boolean",
               list: "array"}


def _field_to_property(spec: Dict[str, Any]) -> Dict[str, Any]:
    """Derive one JSON-Schema property from a field-table entry."""
    prop: Dict[str, Any] = {"type": _JSON_TYPES[spec["type"]]}
    # JSON has one number type; integral floats are fine for "number" but an
    # "integer" field must stay integral.
    if spec.get("enum"):
        prop["enum"] = list(spec["enum"])
    if spec.get("default") is not None:
        prop["default"] = spec["default"]
    flr = spec.get("flrcif")
    if flr:
        prop["x-flrcif-item"] = flr
    if spec.get("authored"):
        prop["description"] = spec["authored"]
    prop["x-dialects"] = list(spec.get("dialects", ()))
    return prop


def _object_schema(fields: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    required = sorted(n for n, s in fields.items() if s.get("required"))
    schema: Dict[str, Any] = {
        "type": "object",
        "properties": {n: _field_to_property(s) for n, s in fields.items()},
        # Unknown keys are preserved by readers/writers but are not silently
        # part of the format: additionalProperties stays true so old files
        # validate, and validate() reports unknown keys as warnings.
        "additionalProperties": True,
    }
    if required:
        schema["required"] = required
    return schema


def to_json_schema() -> Dict[str, Any]:
    """Derive the JSON-Schema document for the network-dialect fps.json.

    The shipped ``data/fps_json_schema.json`` is this function's output; a
    test regenerates it and fails on drift, so the Python tables here stay the
    single authored definition.
    """
    position = _object_schema(POSITION_FIELDS)
    distance = _object_schema(DISTANCE_FIELDS)
    score_set = _object_schema(SCORE_SET_FIELDS)
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://integrativemodeling.org/schemas/bff/fps.json",
        "title": "fps.json — FRET labelling positions and distances",
        "x-schema-version": SCHEMA_VERSION,
        "type": "object",
        "properties": {
            "Positions": {"type": "object",
                          "additionalProperties": position},
            "Distances": {"type": "object",
                          "additionalProperties": distance},
            "χ²": {"type": "object",
                   "additionalProperties": score_set},
            "Evaluators": {"type": "array", "items": {"type": "object"}},
        },
        "additionalProperties": True,
        "$defs": {
            "position": position,
            "distance": distance,
            "score_set": score_set,
        },
    }


# ---------------------------------------------------------------------------
# Validation (self-contained; no jsonschema dependency)
# ---------------------------------------------------------------------------

def _check_fields(
    obj: Dict[str, Any],
    fields: Dict[str, Dict[str, Any]],
    where: str,
    errors: List[str],
    warnings: List[str],
) -> None:
    if not isinstance(obj, dict):
        errors.append(f"{where}: expected an object, got {type(obj).__name__}")
        return
    for name, spec in fields.items():
        if name not in obj:
            if spec.get("required"):
                errors.append(f"{where}: missing required field '{name}'")
            continue
        value = obj[name]
        expected = spec["type"]
        ok = isinstance(value, expected)
        # bool is an int subclass; a bool where a number is expected is a bug.
        if expected in (_F, _I) and isinstance(value, bool):
            ok = False
        # ints are acceptable where floats are expected.
        if expected is _F and isinstance(value, int) and not isinstance(value, bool):
            ok = True
        if not ok:
            errors.append(
                f"{where}.{name}: expected {expected.__name__}, "
                f"got {type(value).__name__} ({value!r})")
            continue
        enum = spec.get("enum")
        if enum and value not in enum:
            errors.append(
                f"{where}.{name}: {value!r} is not one of {sorted(enum)}")
    for key in obj:
        if key not in fields:
            warnings.append(f"{where}: unknown field '{key}'")


def validate_position(
    position: Dict[str, Any], name: str = "position"
) -> Tuple[List[str], List[str]]:
    """Validate one position object. Returns ``(errors, warnings)``."""
    errors: List[str] = []
    warnings: List[str] = []
    _check_fields(position, POSITION_FIELDS, name, errors, warnings)
    if isinstance(position, dict):
        stype = position.get("simulation_type", "AV1")
        if stype == "XYZ":
            for k in ("x", "y", "z"):
                if k not in position:
                    errors.append(
                        f"{name}: simulation_type XYZ requires '{k}'")
        elif stype == "AV3":
            for k in ("radius2", "radius3"):
                if float(position.get(k, 0.0) or 0.0) <= 0.0:
                    warnings.append(
                        f"{name}: simulation_type AV3 with non-positive "
                        f"'{k}' behaves like AV1")
    return errors, warnings


def validate_distance(
    distance: Dict[str, Any],
    name: str = "distance",
    position_names: Optional[set] = None,
) -> Tuple[List[str], List[str]]:
    """Validate one distance object. Returns ``(errors, warnings)``."""
    errors: List[str] = []
    warnings: List[str] = []
    _check_fields(distance, DISTANCE_FIELDS, name, errors, warnings)
    if position_names is not None and isinstance(distance, dict):
        for key in ("position1_name", "position2_name"):
            pname = distance.get(key)
            if pname and pname not in position_names:
                errors.append(
                    f"{name}.{key}: '{pname}' is not a defined position")
    return errors, warnings


def validate(payload: Dict[str, Any]) -> Tuple[List[str], List[str]]:
    """Validate a parsed network-dialect fps.json payload.

    Parameters
    ----------
    payload : dict
        The full JSON document (``Positions``/``Distances``/``χ²``/...).

    Returns
    -------
    (errors, warnings) : (list of str, list of str)
        ``errors`` violate the schema; ``warnings`` flag unknown fields and
        suspicious-but-legal values. An empty ``errors`` list means the file
        conforms.
    """
    errors: List[str] = []
    warnings: List[str] = []
    if not isinstance(payload, dict):
        return [f"payload: expected an object, got {type(payload).__name__}"], []

    positions = payload.get("Positions", {})
    if not isinstance(positions, dict):
        errors.append("Positions: expected an object")
        positions = {}
    for pname, pos in positions.items():
        e, w = validate_position(pos, f"Positions[{pname!r}]")
        errors += e
        warnings += w

    distances = payload.get("Distances", {})
    if not isinstance(distances, dict):
        errors.append("Distances: expected an object")
        distances = {}
    for dname, dist in distances.items():
        e, w = validate_distance(
            dist, f"Distances[{dname!r}]", position_names=set(positions))
        errors += e
        warnings += w

    score_sets = payload.get("χ²", {})
    if not isinstance(score_sets, dict):
        errors.append("χ²: expected an object")
        score_sets = {}
    for sname, sset in score_sets.items():
        e, w = [], []
        _check_fields(sset, SCORE_SET_FIELDS, f"χ²[{sname!r}]", e, w)
        errors += e
        warnings += w
        if isinstance(sset, dict):
            for ref in sset.get("distances", []) or []:
                if ref not in distances:
                    errors.append(
                        f"χ²[{sname!r}]: '{ref}' is not a defined distance")

    evaluators = payload.get("Evaluators")
    if evaluators is not None and not isinstance(evaluators, list):
        errors.append("Evaluators: expected an array")

    return errors, warnings
