"""``IMP.bff.label`` -- what is attached where, and what quenches it.

The system layer: a Label is a dye at a position on a structure, a Quencher
is a moiety that deactivates it. The C++ kernels (StripMask, PETQuenching,
SequenceAlignment) are in their own headers; the IMP API glue (backbone_frame,
attach_dyes, strip_hierarchy) and the Label dataclass are in
:file:`pyext/IMP_bff.label.i` as %pythoncode. This module re-exports the surface
so ``from IMP.bff.label import ...`` keeps working.
"""

from IMP.bff import (
    BACKBONE_ATOM_NAMES,
    FLUOROPHORE_TYPES,
    LABEL_FLRCIF_ITEMS,
    Label,
    PETParameters,
    QUENCHER_FLRCIF_ITEMS,
    Quencher,
    REFERENCE_DYE,
    SITE_KEEP_ATOM_NAMES,
    StripSelection,
    _atom_name,
    _atom_type_from_name,
    _find_atom,
    _get_atom_particles,
    _get_residue_decorator,
    _to_vec,
    align_hierarchies,
    attach_dyes,
    backbone_frame,
    backbone_frame_from_coords,
    backbone_transformation,
    backbone_transformation_from_coords,
    default_strip_mask,
    find_fp_domains,
    frame_to_transformation,
    get_anchor_cb_position,
    load_fp_library,
    parse_plddt_from_pdb,
    parse_strip_mask,
    place_dye,
    place_dye_from_coords,
    place_dye_from_rotamer_cb,
    reference_pet_parameters,
    reference_quenchers,
    resolve_dye_site,
    segments_from_plddt,
    select_atoms,
    site_strip_mask,
    strip_hierarchy,
    strip_obstacles,
    strip_pdb_lines,
    strip_sidechain_at_site,
)

__all__ = [
    'BACKBONE_ATOM_NAMES',
    'FLUOROPHORE_TYPES',
    'LABEL_FLRCIF_ITEMS',
    'Label',
    'PETParameters',
    'QUENCHER_FLRCIF_ITEMS',
    'Quencher',
    'REFERENCE_DYE',
    'SITE_KEEP_ATOM_NAMES',
    'StripSelection',
    'align_hierarchies',
    'attach_dyes',
    'backbone_frame',
    'backbone_frame_from_coords',
    'backbone_transformation',
    'backbone_transformation_from_coords',
    'default_strip_mask',
    'find_fp_domains',
    'get_anchor_cb_position',
    'load_fp_library',
    'parse_plddt_from_pdb',
    'parse_strip_mask',
    'place_dye',
    'place_dye_from_coords',
    'place_dye_from_rotamer_cb',
    'reference_pet_parameters',
    'reference_quenchers',
    'resolve_dye_site',
    'segments_from_plddt',
    'select_atoms',
    'site_strip_mask',
    'strip_hierarchy',
    'strip_obstacles',
    'strip_pdb_lines',
    'strip_sidechain_at_site',
]
