name: doc
channels:
    - tpeulen
    - conda-forge
dependencies:
    - python=3.10
    - doxygen
    - numba
    - scipy
    - pillow
    - sphinx-gallery
    - nbsphinx
    - pandoc
    - imp.bff
    - ipykernel
    - jupyter_client # needed for nbsphinx
    - sphinx_rtd_theme
    - matplotlib
    - numpy
    - numpydoc
    - xeus-cling
    - gcc_linux-64=9.4.0
    - pyyaml
    - graphviz
    - sphinxcontrib-bibtex
    - sphinxcontrib-websupport
    - openmm
    - tqdm
