name: doc
channels:
    - tpeulen
    - conda-forge
dependencies:
    - python
    - doxygen
    - numba
    - scipy
    - pillow
    - pandoc
    - imp.bff
    - ipykernel
    - jupyter_client # needed for nbsphinx
    - sphinx < 7.0
    - nbsphinx
    - sphinx 4.5.*
    - sphinx_rtd_theme
    - sphinx-gallery 0.14.*
    - sphinxcontrib-bibtex
    - sphinxcontrib-websupport
    - matplotlib
    - numpy
    - numpydoc
    - pyyaml
    - graphviz
    - openmm
    - tqdm
