{% set version = "0.10.0" %}
{% set imp = "2.17" %}

package:
  name: imp.bff
  version: {{ version }}

source:
  path: ../

build:
  number: 1
  detect_binary_files_with_prefix: True  # [not win]

requirements:
  build:
    - python {{ python }}
    - numpy {{ numpy }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pkg-config   # [not win]
    - swig
    - cmake
    - ninja
    - graphviz
  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - boost-cpp
    - hdf5
    - eigen
    - fftw
    - mpir  # [win]
    - msmpi  # [win]
    - libmongoc
    - imp
  run:
    - {{ pin_compatible('numpy') }}
    - python {{ python }}
    - imp
    - boost-cpp
    - libmongoc
    - pandas
    - mdtraj
    - tqdm
    - click
    - click-didyoumean

test:
  imports:
    - IMP.bff
  commands:
    - imp_bff --help

about:
  home: https://github.com/tpeulen/imp.bff
  license: 'Mozilla Public License 2.0 (MPL 2.0)'
  summary: |
    Bayesian Framework for Fluorescence for the integrative modeling platform
  description: |
    The Bayesian Framework for Fluorescence (BFF) for the integrative modeling 
    platform (IMP) is C++ software with Python wrappers. IMP.bff was deigned for
    Bayesian analysis of spectroscopic data.
  doc_url: https://docs.peulen.xyz/imp.bff

extra:
  recipe-maintainers:
    - tpeulen

