{% set version = "0.10.0" %}

package:
  name: imp.bff
  version: {{ version }}

source:
  path: ../

build:
    number: 0
    detect_binary_files_with_prefix: True  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy
    - cmake
    - swig
    - ninja
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pkg-config   # [not win]
    - doxygen
  host:
    - boost-cpp
    - libmongoc
    - eigen
    - imp
    - python
    - numpy
  run:
    - boost-cpp
    - libmongoc
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - mdtraj
    - imp
    - tqdm
    - click
    - click-didyoumean

test:
  imports:
    - IMP.bff
  requires:
    - imp
    - python
  commands:
    - imp_bff --help

about:
  home: https://github.com/tpeulen/imp.bff
  license: 'Mozilla Public License 2.0 (MPL 2.0)'
  summary: |
    Bayesian Framework for Fluorescence for the integrative modeling platform
  description: |
    The Bayesian Framework for Fluorescence (BFF) for the integrative modeling 
    platform (IMP) is C++ software with Python wrappers. IMP.bff was deigned for
    Bayesian analysis of spectroscopic data.
  doc_url: https://docs.peulen.xyz/imp.bff

extra:
  recipe-maintainers:
    - tpeulen

