{% set PY_VER_MAJOR = PY_VER[0] %}
{% set PY_VER_MINOR = PY_VER[2] %}

package:
  name: imp.bff
  version: 0.0.10

source:
  path: ../

build:
    number: 0
    string: py{{ PY_VER_MAJOR }}{{ PY_VER_MINOR }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - python
    - numpy
    - cmake 3.20.*
    - swig
    - ninja
    - pkg-config
    - doxygen
  host:
    - python
    - numpy
    - imp
    - boost-cpp
    - libmongoc
    - librttr
    - eigen
  run:
    - boost-cpp
    - libmongoc
    - librttr
    - python
    - imp
    - numpy
    - numba
    - click
    - click-didyoumean
    - tqdm

test:
  imports:
    - IMP.bff
  requires:
    - imp
    - python

about:
  home: https://github.com/tpeulen/imp.bff
  license: 'Mozilla Public License 2.0 (MPL 2.0)'
  summary: |
    Bayesian Framework for Fluorescence for the integrative modeling platform
  description: |
    The Bayesian Framework for Fluorescence (BFF) for the integrative modeling 
    platform (IMP) is C++ software with Python wrappers. IMP.bff was deigned for
    Bayesian analysis of spectroscopic data.
  doc_url: https://docs.peulen.xyz/imp.bff

extra:
  recipe-maintainers:
    - tpeulen
