{% set default_version = '0.14.3' %}

package:
  name: imp.bff
  version: "{{ environ.get('GIT_DESCRIBE_TAG', default_version) }}"

source:
  path: ../

build:
  number: 1
  detect_binary_files_with_prefix: True  # [not win]

requirements:
  build:
    - python
    - numpy
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pkg-config   # [not win]
    - swig
    - cmake
    - ninja
    - graphviz
  host:
    - python
    - numpy
    - boost-cpp
    - eigen
    - cereal
    - mpir  # [win]
    - msmpi  # [win]
    - imp
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - {{ pin_compatible('imp', max_pin='x.x') }}
    - boost-cpp
    - pandas
    - mdtraj
    - tqdm
    - click
    - click-didyoumean

test:
  # Command line tools
  commands:
    - imp_bff --help

about:
  home: https://github.com/tpeulen/imp.bff
  license: 'Mozilla Public License 2.0 (MPL 2.0)'
  summary: |
    Bayesian Framework for Fluorescence for the integrative modeling platform
  description: |
    The Bayesian Framework for Fluorescence (BFF) for the integrative modeling 
    platform (IMP) is C++ software with Python wrappers. IMP.bff was deigned for
    Bayesian analysis of spectroscopic data.
  doc_url: https://docs.peulen.xyz/imp.bff

extra:
  recipe-maintainers:
    - tpeulen

