#!/usr/bin/env python3
"""Turn a .wgsl file into a C header holding it as a string literal.

The shader is authored as WGSL so it can be read and edited as WGSL, and the
plugin carries it as a literal so that a built `libimp_bff_wgpu` needs no data
file beside it. Run at authoring time, not at build time -- the generated
header is committed, and `test/test_wgsl_header.py` fails if it drifts.

    python utility/wgsl_to_header.py gpu/diffusion.wgsl gpu/diffusion_wgsl.h
"""
import sys
from pathlib import Path


def generate(wgsl_path, symbol):
    text = Path(wgsl_path).read_text(encoding="utf-8")
    if '"' in text or "\\" in text:
        raise SystemExit("%s contains a quote or a backslash; the generator "
                         "escapes neither on purpose, so that the header stays "
                         "readable" % wgsl_path)
    guard = "IMPBFF_%s_H" % symbol.upper()
    out = ["/* Generated by utility/wgsl_to_header.py from %s -- do not edit. */"
           % Path(wgsl_path).name,
           "#ifndef %s" % guard, "#define %s" % guard, "",
           "static const char %s[] =" % symbol]
    for line in text.splitlines():
        out.append('    "%s\\n"' % line)
    out.append("    ;")
    out += ["", "#endif  /* %s */" % guard, ""]
    return "\n".join(out)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    src, dst = sys.argv[1], sys.argv[2]
    symbol = "k" + "".join(w.capitalize() for w in Path(src).stem.split("_")) + "Wgsl"
    Path(dst).write_text(generate(src, symbol), encoding="utf-8")
    print("wrote %s (%s)" % (dst, symbol))
