/**
 *  \file IMP/bff/bff_config.h
 *  \brief The module's configuration header for the standalone (IMP-free) build.
 *
 * In the IMP build this file is generated by IMP's module tooling and pulls
 * in IMP's kernel_config.h. Here it is hand-written: the export macro, the
 * namespace macros, and IMPBFF_STANDALONE, which is what Base.h switches on.
 */
#ifndef IMPBFF_CONFIG_H
#define IMPBFF_CONFIG_H

// IMPBFF_WITH_IMP: this same header serves the build that links a private
// IMP (PRD-139). There the module's vocabulary comes from IMP itself, so the
// standalone branch of Base.h must stay switched off, while the export
// macros and the three data-path declarations below are wanted either way.
#if !defined(IMPBFF_WITH_IMP) && !defined(IMPBFF_STANDALONE)
#define IMPBFF_STANDALONE 1
#endif

#include <string>

#if defined(SWIG)
#define IMPBFFEXPORT
#define IMPBFF_EXPORT_TEMPLATE(name)
#elif defined(_MSC_VER)
#define NOMINMAX
#ifdef IMPBFF_EXPORTS
#define IMPBFFEXPORT __declspec(dllexport)
#else
#define IMPBFFEXPORT __declspec(dllimport)
#endif
#define IMPBFF_EXPORT_TEMPLATE(name) template class IMPBFFEXPORT name
#else
#define IMPBFFEXPORT __attribute__((visibility("default")))
#define IMPBFF_EXPORT_TEMPLATE(name) static_assert(true, "")
#endif

#define IMPBFF_BEGIN_NAMESPACE namespace IMP { namespace bff {
#define IMPBFF_END_NAMESPACE } }
#define IMPBFF_BEGIN_INTERNAL_NAMESPACE IMPBFF_BEGIN_NAMESPACE namespace internal {
#define IMPBFF_END_INTERNAL_NAMESPACE } IMPBFF_END_NAMESPACE

#define IMP_BFF_HAS_IMP_ALGEBRA 0
#define IMP_BFF_HAS_IMP_KERNEL 0

namespace IMP { namespace bff {
//! The version of the standalone build, set by its CMake.
IMPBFFEXPORT std::string get_module_version();
//! A file under the module's data directory (IMP's tooling generates these; here src/standalone/Config.cpp).
IMPBFFEXPORT std::string get_data_path(std::string file_name);
//! A file under the module's examples directory.
IMPBFFEXPORT std::string get_example_path(std::string file_name);
} }

#endif  // IMPBFF_CONFIG_H
