name: Build Documentation

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build Documentation
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: doc
          environment-file: doc/environment.yml
          mamba-version: "*"
          channels: conda-forge,tpeulen,defaults
          channel-priority: true
          auto-activate-base: false
      - run: |
          conda info
          conda list
          cd doc
          make

      - uses: bxb100/action-upload@main
        with:
          provider: webdav
          provider_options: |
            endpoint=${{ secrets.WEBDAV_ADDRESS }}
            username=${{ secrets.WEBDAV_USERNAME }}
            password=${{ secrets.WEBDAV_PASSWORD }}
            root=/www/docs.peulen.xyz/project/bff/master/
          include: './doc/_build/html/stable/**'
