
name: Build and upload conda packages

on:
  release:
    types: ['released', 'prereleased']

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: publish-to-conda
        uses: MichaelsJP/conda-package-publish-action@v1.0.0
        with:
          subDir: 'conda-recipe'
          AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
          platforms: 'all'
          override: true
          dry_run: true
